jobs:
  build:
    docker:
      - image: cimg/python:3.6
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              poetry install
        - run:
            name: Run flake8 test
            command: |
                poetry run flake8 --statistics
